[package]
name = "kirpticc-api"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web = "4"
actix-web-lab = "0.10"
actix-cors = "0.6"

juniper = "0.15"

env_logger = "0.9"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
