version: '3.7'

services:
  kripticc-backend:
    build:
      context: .
    container_name: kripticcBackend
    ports:
      - '8000:8000'
    restart: always
    volumes:
      - ./:/BeameBackend
  kripticc-db:
    image: 'postgres:latest'
    ports:
      - '5432:5431'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=dev
      - POSTGRES_DB=kripticc-local-db
    restart: unless-stopped