version: '3.7'

services:
  kripticc-backend:
    build:
      context: .
    container_name: kripticcBackend
    ports:
      - '3001:3001'
    restart: always
    volumes:
      - ./:/BeameBackend
    command: npm run dev